In [0]:
import pandas as pd
import numpy as np

## Loading the Dataset

In [0]:
df=pd.read_csv("/Workspace/Users/siganithin@gmail.com/DbAcademy/Combined_dataset.csv")
df.head()

   product_id  ...   category
0     8376765  ...  backpacks
1     9136281  ...  backpacks
2    17633752  ...  backpacks
3     1376949  ...  backpacks
4    13939916  ...  bath-robe

[5 rows x 24 columns]

##Data Exploration

In [0]:
df.tail()

     product_id  ...   category
995    13698258  ...    watches
996    16896006  ...    watches
997     1708108  ...    watches
998    19280114  ...    watches
999    18601682  ...  yoga-mats

[5 rows x 24 columns]

In [0]:
print(df.shape)

(1000, 24)

In [0]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [0]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [0]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [0]:
print("Total missing values:",df.isnull().sum().sum())

Total missing values: 2639

##Handling Missing Values

In [0]:
df['discount'].fillna(df['discount'].median(),inplace=True)

In [0]:
df['seller_name'].fillna(df['seller_name'].mode()[0],inplace=True)

In [0]:
df['seller_information'].fillna(df['seller_information'].mode()[0],inplace=True)

In [0]:
df.drop(columns=['videos'],inplace=True)

In [0]:
df.drop(columns=['what_customers_said'],inplace=True)

In [0]:
df.drop(columns=['variations'],inplace=True)

In [0]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
dtype: int64

##Basic Operations

In [0]:
#selecting important colummns
df[['title','rating','discount','final_price','delivery_options']].head()

            title  ...                                   delivery_options
0     Lino Perros  ...  ["100% Original Products","Pay on delivery mig...
1  Tommy Hilfiger  ...  ["100% Original Products","Pay on delivery mig...
2           Lavie  ...  ["100% Original Products","Pay on delivery mig...
3          F Gear  ...  ["100% Original Products","Pay on delivery mig...
4       MYTRIDENT  ...  ["100% Original Products","Pay on delivery mig...

[5 rows x 5 columns]

In [0]:
#filtering for high rating
high_rating= df[df['rating']>4.5]
high_rating.head()

    product_id  ...   category
4     13939916  ...  bath-robe
7     18602872  ...  bedsheets
22    21427828  ...      boots
32    18656766  ...        bra
38    21873792  ...   bracelet

[5 rows x 21 columns]

In [0]:
#for high discount
high_discount = df[df['discount']>65]
high_discount.head()

    product_id  ...   category
11    18346118  ...  bedsheets
12    18327434  ...  bedsheets
16    20296382  ...  bedsheets
17    18346134  ...  bedsheets
18    22409156  ...      belts

[5 rows x 21 columns]

In [0]:
#for intial price higher(premium products)
premium_products=df[df['initial_price']>7000]
premium_products.head()

    product_id  ...      category
21     1728397  ...         boots
22    21427828  ...         boots
58    20129438  ...  casual-shoes
76    17312144  ...  casual-shoes
77    17350218  ...  casual-shoes

[5 rows x 21 columns]

In [0]:
#combining both rating and discount for the best deals
best_deals=df[(df['rating']>4.5) & (df['discount']>65)]
best_deals.head()

     product_id  ...  category
38     21873792  ...  bracelet
128    17692718  ...   dresses
133    18996672  ...   dresses
155    20046216  ...   dresses
169    13406942  ...   dresses

[5 rows x 21 columns]

In [0]:
print("highly rated products:",len(high_rating))
print("highly discounted products:",len(high_discount))
print("premium products:",len(premium_products))
print("best deals:",len(best_deals))

highly rated products: 104
highly discounted products: 227
premium products: 39
best deals: 18

##Removing duplicates

In [0]:
#checking whether duplicates exist or not
duplicate_count=df.duplicated().sum()
print("Duplicates before removing:",duplicate_count)

Duplicates before removing: 0

In [0]:
#duplicates doesnt exist in dataset 
#if a dataset has any duplicates then we should do
df=df.drop_duplicates()

##Derived Column creation

**Creating a column for  total amount**

since the dataset doesn't contain quantity column , so total_amount is calculated using the initial price and discount 

formula : total amount = initial pricce - (initial price * discount / 100)

In [0]:
df['total_amount']=df['initial_price']-(df['initial_price']*df['discount']/100)
print(df['total_amount'].head())

0    1677.90
1    1884.35
2    1049.65
3     804.00
4    2406.17
Name: total_amount, dtype: float64

In [0]:
df.head()

   product_id           title  ...   category  total_amount
0     8376765     Lino Perros  ...  backpacks       1677.90
1     9136281  Tommy Hilfiger  ...  backpacks       1884.35
2    17633752           Lavie  ...  backpacks       1049.65
3     1376949          F Gear  ...  backpacks        804.00
4    13939916       MYTRIDENT  ...  bath-robe       2406.17

[5 rows x 22 columns]

In [0]:
df.to_csv('/tmp/cleaned_dataset.csv',index=False)
print("cleaned dataset saved successfully")

cleaned dataset saved successfully